name: build and deploy downloader
on: [push]

jobs:
  Buildah-Test:
    runs-on: arc-runners
    container:
      image: quay.io/buildah/stable:v1.32.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        run: cd src/downloader && buildah bud --authfile /etc/runners-secrets/kaniko.json -f Dockerfile -t r.compredict.xyz/downloader:latest .
      - name: push
        run: buildah push --authfile /etc/runners-secrets/kaniko.json r.compredict.xyz/downloader:latest
          #Build-Downloader:
          #  runs-on: arc-runners
          #  container:
          #    image: r.compredict.xyz/kaniko:latest
          #  steps:
          #    - name: Checkout
          #      uses: actions/checkout@v4
          #    - name: Symlink auth
          #      run: ln -s /etc/runners-secrets/kaniko.json /kaniko/.docker/config.json
          #    - name: Build and push
          #      run: cd src/downloader && /bin/kaniko-executor -f Dockerfile -c . -d r.compredict.xyz/downloader:latest
