name: Build forecast
on:
  push:
    paths:
      - src/models/**
      - src/data/**
      - src/run_all.py
      - src/requirements.txt
      - src/requirements_lock.txt
      - src/Dockerfile
      - src/run_all_config.yaml

jobs:
  Build-N-Push-Forecast:
    uses: ./.github/workflows/forecast-build.yml
  Deploy-Forecast:
    needs: ["Build-N-Push-Forecast"]
    uses: ./.github/workflows/forecast-deploy.yml
