name: compredict k8s run actions
on:
  workflow_dispatch:

jobs:
  Test-Docker:
    runs-on: arc-runners
    container:
      image: python:slim-bullseye
    steps:
      - name: Check python version
        run: python --version
      - name: Check os release
        run: cat /etc/*release*
      - name: Display pwd
        run: pwd
      - name: Display ls
        run: ls -al
      - name: Diplay env
        run: env
  Test-Kaniko:
    runs-on: arc-runners
    container:
      image: r.compredict.xyz/kaniko:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Symlink auth
        run: ln -s /etc/runners-secrets/kaniko.json /kaniko/.docker/config.json
      - name: CAT Symlink auth
        run: cat /kaniko/.docker/config.json
      - name: sleep
        run: sleep 300
      - name: Build and push
        run: /bin/kaniko-executor -f Dockerfile -c . -d r.compredict.xyz/foo:1 --verbosity=trace
