name: compredict k8s run actions
on:
  workflow_dispatch:

jobs:
  Test-Docker:
    runs-on: arc-runners
    container:
      image: python:slim-bullseye
    steps:
      - name: Check python version
        run: python --version
      - name: Check os release
        run: cat /etc/*release*
      - name: Display pwd
        run: pwd
      - name: Display ls
        run: ls -al
      - name: Diplay env
        run: env
  Test-Buildah:
    runs-on: arc-runners
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Sleep
        run: sleep 600
      - name: Checkout
        uses: actions/checkout@v4
      - name: Symlink auth
        run: ln -s /etc/runners-secrets/kaniko.json /kaniko/.docker/config.json
      - name: Build and push
        run: /kaniko/executor -f Dockerfile -c . -d r.compredict.xyz/foo:1
