name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Test-Docker:
    runs-on: arc-runners
    container:
      image: python:slim-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check python version
        run: python --version
      - name: Check os release
        run: cat /etc/*release*
      - name: Display pwd
        run: pwd
      - name: Display ls
        run: ls -al
      - name: Diplay env
        run: env
